FROM node:16-alpine
WORKDIR '/app'
ENV CI=true
COPY package.json .
RUN npm install
RUN file="$(ls -1 /app)" && echo $file
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .
CMD ["npm", "run", "start"]